### ISSUE TITLE
Erro ao realizar buscas

### ISSUE THREAD

**Issue by quebrandolink** [olucaslopes/BNMP-Scraper#2]
Estou tentando usar o pacote para obter os Mandados, porém estou tendo erro

Se puderem adicionar mais exemplos de utilização para municipios específicos também por gentileza, obrigado.

Sou novo em python então estou tendo dificuldades.

Desde já obrigado.

**Código utilizado**

`from bnmp_scraper import BnmpScraper`
`cookie = 'portalbnmp=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJndWVzdF9wb3J0YWxibm1wIiwiYXV0aCI6IlJPTEVfQU5PTllNT1VTIiwiZXhwIjoxNzI3MTc3NDU5fQ.-6wFlgsslI_SYys0YeYeWch8lCyIk0FdGD-gDF1Z7qr6cVR0VhxgRY-pLoBn8S4yxI0nVmlMWpeVSBRK-kt39g'`

`extrator = BnmpScraper(cookie)`

`mandadosAcre = extrator.estado("PR")`
`mandadosAcre.baixar_mandados()`
`listaMandados = mandadosAcre.data`

`df = pd.json_normalize(mandadosAcre.data)`
`print(listaMandados.lenght)`

**resultado no console**

"BNMP Extrator/main.py" 

<Response [400]>
Traceback (most recent call last):
  File "BNMP Extrator\venv\lib\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BNMP Extrator\main.py", line 9, in <module>
    mandadosAcre.baixar_mandados()
  File "BNMP Extrator\venv\lib\site-packages\bnmp_scraper\api.py", line 100, in baixar_mandados
    mandados_parciais = self._request_post_expandido(self._init_info, self._id)
  File "BNMP Extrator\venv\lib\site-packages\bnmp_scraper\filtro.py", line 115, in _request_post_expandido
    novos_mandados = list(executor.map(self._request_post, params, repeat(data)))
  File "C:\Python310\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "BNMP Extrator\venv\lib\site-packages\bnmp_scraper\filtro.py", line 65, in _request_post
    responsetxt = response.json().get('detail', '')
  File "BNMP Extrator\venv\lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1

**Comment by juditecypreste** [comment]
Estou tendo o mesmo problema. Às vezes ele também retorna o JSONDecodeError: Expecting value: line 1 column 1 (char 0).
